/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID cad13)
#  Generated on:      Sun Nov  2 22:02:03 2025
#  Design:            processor2stage
#  Command:           saveNetlist processor2stage.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Nov  2 2025 21:47:51 IST (Nov  2 2025 16:17:51 UTC)
// Verification Directory fv/processor2stage 
module processor2stage (
	clk, 
	reset, 
	result_out, 
	pc_out);
   input clk;
   input reset;
   output [7:0] result_out;
   output [7:0] pc_out;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;

   assign result_out[0] = 1'b0 ;
   assign result_out[1] = 1'b0 ;
   assign result_out[2] = 1'b0 ;
   assign result_out[3] = 1'b0 ;
   assign result_out[4] = 1'b0 ;
   assign result_out[5] = 1'b0 ;
   assign result_out[6] = 1'b0 ;
   assign result_out[7] = 1'b0 ;

   SDFFRHQX1 \PC_reg[7]  (.CK(clk),
	.D(n_0),
	.Q(pc_out[7]),
	.RN(n_16),
	.SE(n_14),
	.SI(pc_out[7]));
   DFFRHQX1 \PC_reg[6]  (.CK(clk),
	.D(n_15),
	.Q(pc_out[6]),
	.RN(n_16));
   OA21XL g6292__2398 (.A0(pc_out[6]),
	.A1(n_12),
	.B0(n_14),
	.Y(n_15));
   DFFRHQX1 \PC_reg[5]  (.CK(clk),
	.D(n_13),
	.Q(pc_out[5]),
	.RN(n_16));
   AOI2BB1XL g6295__5107 (.A0N(pc_out[5]),
	.A1N(n_10),
	.B0(n_12),
	.Y(n_13));
   NAND2XL g6294__6260 (.A(pc_out[6]),
	.B(n_12),
	.Y(n_14));
   DFFRHQX1 \PC_reg[3]  (.CK(clk),
	.D(n_9),
	.Q(pc_out[3]),
	.RN(n_16));
   AOI21XL g6298__4319 (.A0(n_7),
	.A1(n_8),
	.B0(n_10),
	.Y(n_11));
   AND2X1 g6297__8428 (.A(pc_out[5]),
	.B(n_10),
	.Y(n_12));
   OA21XL g6301__5526 (.A0(pc_out[3]),
	.A1(n_6),
	.B0(n_8),
	.Y(n_9));
   NOR2XL g6300__6783 (.A(n_7),
	.B(n_8),
	.Y(n_10));
   NAND2XL g6303__3680 (.A(pc_out[3]),
	.B(n_6),
	.Y(n_8));
   AOI21XL g6304__1617 (.A0(n_4),
	.A1(n_3),
	.B0(n_6),
	.Y(n_5));
   DFFRHQX1 \PC_reg[1]  (.CK(clk),
	.D(n_2),
	.Q(pc_out[1]),
	.RN(n_16));
   NOR2XL g6306__2802 (.A(n_4),
	.B(n_3),
	.Y(n_6));
   OA21XL g6307__1705 (.A0(pc_out[0]),
	.A1(pc_out[1]),
	.B0(n_3),
	.Y(n_2));
   NAND2XL g6309__5122 (.A(pc_out[0]),
	.B(pc_out[1]),
	.Y(n_3));
   INVXL g6314 (.A(pc_out[7]),
	.Y(n_0));
   INVXL g6313 (.A(reset),
	.Y(n_16));
   DFFRX1 \PC_reg[0]  (.CK(clk),
	.D(n_1),
	.Q(pc_out[0]),
	.QN(n_1),
	.RN(n_16));
   DFFRX1 \PC_reg[2]  (.CK(clk),
	.D(n_5),
	.Q(pc_out[2]),
	.QN(n_4),
	.RN(n_16));
   DFFRX1 \PC_reg[4]  (.CK(clk),
	.D(n_11),
	.Q(pc_out[4]),
	.QN(n_7),
	.RN(n_16));
endmodule

